name: Deploy WinForms App to AWS AppStream

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest  # ✅ Uses Windows Runner

    steps:
    # 1️⃣ Checkout the WinForms App Source Code
    - name: Checkout Repository
      uses: actions/checkout@v3

    # 2️⃣ Set Image Name with Timestamp
    - name: Generate Timestamped Image Name
      shell: pwsh
      run: |
        $timestamp = Get-Date -Format "yyyyMMdd_HHmm"
        echo "IMAGE_NAME=$por-base-image-$timestamp" | Out-File -FilePath $env:GITHUB_ENV -Append

    # 3️⃣ Setup .NET for Windows Build
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  # Change to match your .NET version

    # 4️⃣ Build WinForms Application
    - name: Build WinForms App
      run: |
        dotnet publish -c Release -r win-x64 -o ./publish

    # 5️⃣ Configure AWS CLI
    - name: Configure AWS CLI
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region ${{ secrets.AWS_REGION }}

   # 6️⃣ Install WinForms App on Image Builder
    - name: Install WinForms App on Image Builder
      shell: pwsh
      run: |
        aws ssm send-command --document-name "AWS-RunPowerShellScript" `
          --targets Key=tag:Name,Values="por_tf_appstream_image_builder" `
          --parameters '{"commands":["New-Item -ItemType Directory -Path \"C:\\Apps\\POR\" -Force; Copy-Item -Path \"./publish/*\" -Destination \"C:\\Apps\\POR\" -Recurse -Force"]}'

    # 7️⃣ Create a New AppStream Image from Image Builder
    - name: Create New AppStream Image
      shell: pwsh
      run: |
        aws appstream create-updated-image --destination-image-name "$env:IMAGE_NAME" `
          --source-image-name "por_tf_appstream_image_builder"

    # 8️⃣ Wait for Image Creation to Complete
    - name: Wait for Image Creation
      shell: pwsh
      run: |
        do {
          Start-Sleep -Seconds 60
          $STATUS = aws appstream describe-images --name "$env:IMAGE_NAME" --query "Images[0].State" --output text
          echo "Current Status: $STATUS"
        } while ($STATUS -ne "AVAILABLE")

    # 9️⃣ Update Fleet to Use New Image
    - name: Update AppStream Fleet with New Image
      shell: pwsh
      run: |
        aws appstream update-fleet --name "${{ secrets.APPSTREAM_FLEET_NAME }}" --image-name "$env:IMAGE_NAME"

    # 🔟 Restart Fleet to Apply New Image
    - name: Restart AppStream Fleet
      shell: pwsh
      run: |
        aws appstream stop-fleet --name "${{ secrets.APPSTREAM_FLEET_NAME }}"
        aws appstream start-fleet --name "${{ secrets.APPSTREAM_FLEET_NAME }}"
